plugins:
  - name: "gcp"
    enabled: true
    type: checks
    source: "github.com/padok-team/yatas-gcp"
    version: "local"
    description: "Check for GCP good practices"

pluginsConfiguration:
  - pluginName: "gcp"
    accounts:
      - project: "padok-university"
